name: Deploy Mobile App

on:
  push:
    tags:
      - "app-v*"

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    defaults:
      run:
        working-directory: ./main-app

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 24.x

      - name: Install Dependencies
        run: npm install

      - name: Install EAS CLI
        run: npm install -g eas-cli

      - name: Build Android APK
        env:
          EXPO_TOKEN: ${{ secrets.EXPO_TOKEN }}
        run: eas build --platform android --profile preview --non-interactive

      - name: Download APK from Expo
        env:
          EXPO_TOKEN: ${{ secrets.EXPO_TOKEN }}
        run: |
          eas build:download --platform android --latest
          mv *.apk ray-brook-app.apk

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: main-app/ray-brook-app.apk
          generate_release_notes: true
