name: Deploy Mobile App

on:
  push:
    tags:
      - "app-v*"

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./main-app

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 24.x

      - name: Install Dependencies
        run: npm install

      - name: Install EAS CLI
        run: npm install -g eas-cli

      - name: Build Android APK
        env:
          EXPO_TOKEN: ${{ secrets.EXPO_TOKEN }}
        run: eas build --platform android --profile preview --non-interactive
