name: Deploy Mobile App

on:
  push:
    tags:
      - "app-v*"

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    defaults:
      run:
        working-directory: ./main-app

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 22.x

      - name: Install Dependencies
        run: npm ci

      - name: Install EAS CLI
        run: npm install -g eas-cli

      - name: Build and Download APK
        env:
          EXPO_TOKEN: ${{ secrets.EXPO_TOKEN }}
        run: |
          echo "Starting EAS cloud build..."
          eas build --platform android --profile preview --non-interactive --json > build-output.json

          APK_URL=$(jq -r 'if type=="array" then .[0].artifacts.buildUrl else .artifacts.buildUrl end' build-output.json)

          echo "Build finished! Downloading APK from: $APK_URL"

          curl -L -o ray-brook-app.apk "$APK_URL"

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: main-app/ray-brook-app.apk
          generate_release_notes: true
