name: Package Chrome Extension

on:
  push:
    tags:
      - "ext-v*"

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Zip Extension
        run: |
          cd browser-extension
          zip -r ../ray-brook-extension.zip . -x "*.git*"

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: ray-brook-extension.zip
          generate_release_notes: true
